name: Reuseable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployment artifact files
        required: true
        default: dist
        type: string
jobs:
  deploy2:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifacts@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading..."
